trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'tangentkyle/firstapi'
  dockerId: 'tangentkyle'

steps:
- script: docker build -f WebApplication1/WebApplication1/Dockerfile -t $(imageName) .
- script: docker login -u $(dockerId) -p $(pswd)
- script: docker push $(imageName)
- task: CopyFiles@2
  inputs:
    sourceFolder: $(WebApplication1/WebApplication1)
    contents: '**/mydeploy.yaml'
    targetFolder: $(Build.ArtifactStagingDirectory)
    overWrite: true
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'drop' 
  displayName: 'docker build'

