apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: firstapi
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: firstapi
    spec:
      containers:
        - image: "tangentkyle/firstapi"
          imagePullPolicy: Always
          name: firstapi
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: firstapi
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: firstapi
